### ISSUE TITLE
App disappears when there is no space

### ISSUE THREAD

**Issue by Lynx901** [kmikiy/SpotMenu#71] opened 2017-10-22 11:25 UTC
When the title/artist of the song is too long and it "gets in conflict" with the menu options of the program you are using (for example Chrome), SpotMenu just disappears and it doesn't leave any icon or anything... 
Chrome screenshot:
![image](https://user-images.githubusercontent.com/9676003/31861359-2b52e0f2-b72c-11e7-9a7a-26a663365637.png)
Spotify screenshot:
![image](https://user-images.githubusercontent.com/9676003/31861361-304da0f6-b72c-11e7-9e44-4c76aae29f56.png)

So my question is if there is any possibility that the title+artist string gets "chopped" with something like suspension points (...) or something so you can access to SpotMenu even if the menu options are too wide.

**Comment by kmikiy** [comment] 2017-10-22 14:20
Yep, I’ve experienced this as well. Sadly the operating system doesnt notify the app if it has been hidden. And there is basically no official way to tell if the app has been hidden from the app itself. This is similar to issue #16 . The best/easiest thing I could implement is have a user preference for max character length allowed and truncate text above the limit.

**Comment by Zazerr** [comment] 2017-11-05 01:08
A possible solution could be to just make the text roll back and forwards, or just roll completely off then roll back on, from the right to left so you can read it.

**Comment by BlackHawk2306** [comment] 2017-12-27 05:12
Yep, since my Hackintosh, yep, I plead guilty ;), only runs on a 1280x800 monitor, I'll buy a FullHD one, but atm, that's what I got, I know this issue, it is not THAT hard for a title to not fit in on that 1280 pixels wide 19" display xD
Making it a scrolling text in case it is too long, like in Spotify itself (top left cornder where the album art is) should be an easy way to solve this.

**Comment by kmikiy** [comment] 2017-12-27 09:36
i'm closing this issue as it is basically a duplicate of #16

**Closed by kmikiy** 2017-12-27 09:36 UTC
Labels: duplicate, help wanted
