### ISSUE TITLE
Great App! Feature Request: Optional showing Play/Pause & Skip button in Menu (like Skip Tunes app)

### ISSUE THREAD

**Issue by Castrano** [kmikiy/SpotMenu#108] opened 2018-01-10 18:59 UTC
Sorry, this isn't a bug/issue, just a feature request.

I've been using Skip Tunes, but the design of your app is much nicer. Wondering if at some point it might be possible to add an option for displaying a Play/Pause button and Skip button attached to the main icon, akin to what Skip Tunes does. I do find myself missing that quick functionality right there in the menu.

Thanks!

**Comment by Castrano** [comment] 2018-01-10 19:03
Just to clarify... I'm attaching an image of what the Skip Tunes menu looks like:

<img width="59" alt="skip tunes" src="https://user-images.githubusercontent.com/35308982/34790191-dd310454-f5f5-11e7-99d6-f4769aa994dc.png">

**Comment by kmikiy** [comment] 2018-01-11 12:05
I'm glad you like the app 🙌🏻 I'm closing this issue because it is a duplicate of #74

**Closed by kmikiy** 2018-01-11 12:05 UTC
