### ISSUE TITLE
Hide title when paused

### ISSUE THREAD

**Issue by mrleblanc101** [kmikiy/SpotMenu#51] opened 2017-08-16 03:14 UTC
Hi,
It would be great to hide the song title when Spotify is paused because most people never quit their Mac app it can become annoying to always see the title since it can take a lot of place in the menu bar.

**Comment by kmikiy** [comment] 2017-10-25 08:27
closed as it a duplicate of #73

**Closed by kmikiy** 2017-10-25 08:27 UTC
Labels: duplicate, feature request
